diccionario = {
    0: {
        "nombre_cliente": "Joseph",
        "apellido_cliente": "Gregory",
        "contacto": "Charles Lee",
        "correo_electronico": "joseph.gregory@gmail.com",
        "telefono": "+4772802209",
        "sitio_web": "www.saunders.com",
        "otro_perfil": "www.jenkins.com",
    },
    1: {
        "nombre_cliente": "Robert",
        "apellido_cliente": "Miller",
        "contacto": "Anthony Jones",
        "correo_electronico": "robert.miller@gmail.com",
        "telefono": "+3384866922",
        "sitio_web": "cummings-roy.com",
        "otro_perfil": "www.richardson.com",
    },
    2: {
        "nombre_cliente": "Cameron",
        "apellido_cliente": "Ramirez",
        "contacto": "Joseph Calderon",
        "correo_electronico": "cameron.ramirez@hotmail.com",
        "telefono": "+14354775765685",
        "sitio_web": "www.kelly-zamora.com",
        "otro_perfil": "www.mcintyre.org",
    },
    3: {
        "nombre_cliente": "Jeff",
        "apellido_cliente": "Jones",
        "contacto": "Andrew Taylor",
        "correo_electronico": "jeff-jones@yahoo.com",
        "telefono": "+6318540223542",
        "sitio_web": "www.odonnell.com",
        "otro_perfil": "www.eaton.com",
    },
    4: {
        "nombre_cliente": "Sonya",
        "apellido_cliente": "Jefferson",
        "contacto": "Richard Wilson",
        "correo_electronico": "sonya.jefferson@yahoo.com",
        "telefono": "+2664090986",
        "sitio_web": "russell.org",
        "otro_perfil": "www.mayo-george.com",
    },
    5: {
        "nombre_cliente": "Thomas",
        "apellido_cliente": "Allen",
        "contacto": "Ronald Moran",
        "correo_electronico": "thomas-allen@hotmail.com",
        "telefono": "+2972643974",
        "sitio_web": "hill.com",
        "otro_perfil": "www.cooley-sanchez.com",
    },
    6: {
        "nombre_cliente": "Rodney",
        "apellido_cliente": "Hernandez",
        "contacto": "Luis White",
        "correo_electronico": "rodney_hernandez@hotmail.com",
        "telefono": "+165659767121081",
        "sitio_web": "robinson-miles.com",
        "otro_perfil": "www.lester.org",
    },
    7: {
        "nombre_cliente": "Olivia",
        "apellido_cliente": "Walters",
        "contacto": "Joseph Walter",
        "correo_electronico": "olivia.walters@hotmail.com",
        "telefono": "+21196435463550",
        "sitio_web": "www.hill.com",
        "otro_perfil": "www.villarreal.com",
    },
    8: {
        "nombre_cliente": "Rebecca",
        "apellido_cliente": "Gilbert",
        "contacto": "Travis Garcia",
        "correo_electronico": "rebecca.gilbert@gmail.com",
        "telefono": "+133472519811051",
        "sitio_web": "watson-butler.net",
        "otro_perfil": "huffman.com",
    },
}
